'use client';

import Image from 'next/image';
import { artworks, artSourceCredit } from '@/data/artworks';
import { money } from '@/game/format';
import { artDisplayCapacity, artMarketMultiplier, artPortfolioValue, artValue, buyArtwork, normalizeArtPortfolio, sellArtwork, toggleArtworkDisplay } from '@/game/systems/art-market';
import type { GameState } from '@/game/types';

export function ArtDistrictView({state,setState}:{state:GameState;setState:React.Dispatch<React.SetStateAction<GameState|null>>}){
  const portfolio=normalizeArtPortfolio(state.art),capacity=artDisplayCapacity(state.houseLevel),portfolioValue=artPortfolioValue(portfolio),invited=portfolio.ownedIds.length>=3||state.totalSpent>=100_000;
  return <section className="art-district-shell">
    <section className="panel art-hero"><div><span className="eyebrow">ART DISTRICT · COLLECTIONS, HOMES & REPUTATION</span><h2>Put a point of view on your walls.</h2><p>Collect stable Museum Editions from open-access works, take risks on fictional local originals, then curate the pieces that actually live in your home.</p></div><div className="art-hero-stats"><span><small>Portfolio value</small><b>{money(portfolioValue)}</b></span><span><small>On display</small><b>{portfolio.displayedIds.length}/{capacity}</b></span><span><small>Gallery standing</small><b>{invited?'Invited':'Emerging'}</b></span></div></section>
    <section className={`panel curator-invite ${invited?'ready':''}`}><span>{invited?'✉️':'🗝️'}</span><div><span className="eyebrow">CURATOR CIRCLE</span><b>{invited?'Opening-night invitation unlocked':'Your name is starting to circulate'}</b><small>{invited?'Private previews, loans, and future gallery events are now part of your story.':`Own 3 works or spend ${money(100_000)} overall to receive an invitation.`}</small></div></section>
    <section className="art-section-head"><div><span className="eyebrow">THE STREET MARKET</span><h2>Buy, hold, curate, or move on.</h2></div><small>Museum Editions are reproductions. Local originals are fictional in-game works.</small></section>
    <div className="art-grid">{artworks.map((art)=>{const owned=portfolio.ownedIds.includes(art.id),displayed=portfolio.displayedIds.includes(art.id),price=artValue(art),movement=Math.round((artMarketMultiplier(art)-1)*100),entry=portfolio.purchasePrices[art.id],gain=entry?price-entry:0,canDisplay=displayed||portfolio.displayedIds.length<capacity;return <article className={`art-card ${art.kind}`} key={art.id}><div className={`art-frame ${art.imageUrl?'':'fictional-art'}`}>{art.imageUrl?<Image src={art.imageUrl} alt={`${art.title} by ${art.artist}`} width={800} height={800} sizes="(max-width: 700px) 100vw, (max-width: 1120px) 50vw, 33vw"/>:<div className={`fictional-canvas ${art.id}`}><i/><i/><i/></div>}<span>{art.kind==='museum-edition'?'MUSEUM EDITION':'LOCAL ORIGINAL'}</span></div><div className="art-card-copy"><div className="art-card-title"><div><h3>{art.title}</h3><p>{art.artist} · {art.year}</p></div><em className={movement>=0?'positive':'negative'}>{movement>=0?'+':''}{movement}%</em></div><p className="art-description">{art.description}</p><div className="art-tags"><span>{art.palette}</span><span>{art.roomBonus}</span></div><div className="art-price"><div><small>{owned?`Current value · ${gain>=0?'+':''}${money(gain)}`:'Today’s asking value'}</small><b>{money(price)}</b></div>{owned?<div className="art-actions"><button className={displayed?'displayed':''} disabled={!canDisplay} onClick={()=>setState((current)=>current?toggleArtworkDisplay(current,art.id):current)}>{displayed?'Remove from wall':canDisplay?'Hang at home':'Wall slots full'}</button><button className="sell-art" onClick={()=>setState((current)=>current?sellArtwork(current,art.id):current)}>Sell · {money(Math.round(price*.9))}</button></div>:<button disabled={state.cash<price} onClick={()=>setState((current)=>current?buyArtwork(current,art.id):current)}>Collect · {money(price)}</button>}</div>{art.kind==='museum-edition'?<small className="art-source">{art.medium} · <a href={art.sourceUrl} target="_blank" rel="noreferrer">National Gallery source ↗</a></small>:<small className="art-source">Values are a fictional game market, not real investment advice.</small>}</div></article>})}</div>
    <section className="panel art-home"><div><span className="eyebrow">YOUR HOME WALL</span><h2>Curated, not hoarded.</h2><p>House level {state.houseLevel} gives you {capacity} display slot{capacity===1?'':'s'}. A displayed piece earns its room-story effect; owning it alone does not.</p></div><div className="home-wall">{portfolio.displayedIds.length?portfolio.displayedIds.map((id)=>{const art=artworks.find((entry)=>entry.id===id);return art?<div key={id} title={art.title}>{art.imageUrl?<Image src={art.imageUrl} alt="" width={180} height={140} sizes="180px"/>:<div className="mini-fictional">✦</div>}<small>{art.roomBonus}</small></div>:null}):<p>Choose a piece and hang it here. Your starter home deserves something more interesting than an empty wall.</p>}</div></section>
    <section className="art-credit"><b>Open-access art credits</b><p>{artSourceCredit} <a href="https://www.nga.gov/artworks/free-images-and-open-access" target="_blank" rel="noreferrer">Explore the National Gallery of Art ↗</a></p><small>The National Gallery of Art logo is not used, and this game is not endorsed by the National Gallery of Art.</small></section>
  </section>
}
