'use client';
import { careerJobs } from '@/data/careers';
import { lifeSkills } from '@/data/life-progression';
import { applyForCareer, careerDailyPay, careerJobUnlocked, currentCareerJob, leaveCareer, normalizeCareer, promoteCareer, requestCareerRaise } from '@/game/systems/careers';
import { lifeSkillLevel } from '@/game/systems/life-progression';
import { money } from '@/game/format';
import type { GameState } from '@/game/types';

export function CareerView({state,setState}:{state:GameState;setState:React.Dispatch<React.SetStateAction<GameState|null>>}){
 const career=normalizeCareer(state.career),current=currentCareerJob(state),pay=careerDailyPay(state);
 if(!state.life.enabled)return null;
 return <section className="panel career-panel"><div className="section-heading"><div><span className="eyebrow">CAREER</span><h2>{current?`${current.emoji} ${current.name}`:'Find stable work'}</h2></div><span>Rep {career.careerReputation} · XP {career.experienceDays}d</span></div>
 {current?<><p className="muted">{current.description} · <b>{money(pay)}/game day</b>. Performance {Math.round(career.performance)}/100 · {career.daysInCurrentJob} days in role.</p><div className="career-current-actions">{current.nextJobId?<button type="button" disabled={!careerJobUnlocked(state,current.nextJobId)||career.performance<65} onClick={()=>setState(s=>s?promoteCareer(s):s)}>Seek promotion</button>:null}<button type="button" disabled={career.daysInCurrentJob<10||career.performance<70} onClick={()=>setState(s=>s?requestCareerRaise(s):s)}>Ask for raise</button><button type="button" onClick={()=>setState(s=>s?leaveCareer(s):s)}>Quit</button></div><small className="muted">Raise ×{career.raiseMultiplier.toFixed(2)} · Raises {career.raises} · Promotions {career.promotions}</small></>:<><p className="muted">Apply for work now. Better roles unlock from skill levels, reputation and performance. Time unemployed is tracked too.</p><small className="muted">Jobs held {career.jobsHeld} · Quits {career.voluntaryQuits} · Layoffs {career.layoffs} · Fired {career.fired} · Unemployed {career.unemploymentDays}d</small></>}
 <div className="career-grid">{careerJobs.map(job=>{const unlocked=careerJobUnlocked(state,job.id),skill=job.requiredSkillId?lifeSkills.find(s=>s.id===job.requiredSkillId):null,level=job.requiredSkillId?lifeSkillLevel(state.life,job.requiredSkillId):0;return <article key={job.id} className={career.jobId===job.id?'selected':''}><header><span>{job.emoji}</span><div><b>{job.name}</b><small>{job.trackId.toUpperCase()}</small></div><em>{money(job.payPerDay)}/day</em></header><p>{job.description}</p><small>{skill?`${skill.name} Lv ${level}/${job.requiredSkillLevel??0}`:'Open entry'}{job.requiredReputation?` · Rep ${career.careerReputation}/${job.requiredReputation}`:''}</small><button type="button" disabled={!unlocked||career.jobId===job.id} onClick={()=>setState(s=>s?applyForCareer(s,job.id):s)}>{career.jobId===job.id?'Current job':unlocked?'Apply':'Locked'}</button></article>})}</div></section>;
}