'use client';

import { useState } from 'react';
import type { GameState } from '@/game/types';
import type { CivicFocus, WorldScale } from '@/game/world-types';
import { townBuildings } from '@/data/town-content';
import { cityEconomySnapshot } from '@/game/systems/city-economy';
import {
  buildDiplomaticTrust, canFoundSatelliteCity, canFundWorldProject, canOpenEmbassy, canSignGlobalVenture, canUpgradeTradeRoute, chooseCivicFocus,
  claimWorldMilestone, civicFocuses, currentWorldEvent, developPlanet, developSatelliteCity,
  establishWorldOutpost, expeditionDestinations, formDiplomaticCompact, foundSatelliteCity,
  embassyCost, fundWorldProject, globalVentures, internationalBusinessSnapshot, milestoneAvailable, normalizeWorld, openCityInitiative, openEmbassy, planetaryUpgradeCost,
  resolveWorldEvent, satelliteCitySnapshot, satelliteCityUpgradeCost, signGlobalVenture, toggleWorldPolicy, tradeRouteCost, tradeSectors, upgradeTradeRoute,
  worldIncomeMultiplier, worldMilestones, worldPolicies, worldProjects, worldResourceInfo, worldScale,
} from '@/game/systems/world';

const zooms: { id: WorldScale; label: string; icon: string }[] = [
  { id: 'town', label: 'Town', icon: '🏘️' }, { id: 'city', label: 'City', icon: '🏙️' }, { id: 'civilization', label: 'Civ', icon: '🏛️' },
  { id: 'country', label: 'Country', icon: '🗺️' }, { id: 'empire', label: 'Empire', icon: '👑' }, { id: 'planet', label: 'Planet', icon: '🌎' }, { id: 'universe', label: 'Universe', icon: '🪐' },
];
const scaleOrder = zooms.map(z => z.id);
const districtLayout = [
  { id: 'hideout', name: 'Your Hideout', icon: '🏠', description: 'The place your journey began.' }, { id: 'sound-booth', name: 'Sound Booth', icon: '🎵', description: 'Music and live events.' },
  { id: 'lokpet-sanctuary', name: 'Lokpet Sanctuary', icon: '🐾', description: 'Companion care and training.' }, { id: 'card-quarter', name: 'Card Quarter', icon: '🃏', description: 'Collecting and the card shop.' },
  { id: 'garden', name: 'Community Garden', icon: '🌱', description: 'A green heart for the town.' }, { id: 'workshop', name: 'Maker Workshop', icon: '🛠️', description: 'Skills and local craft.' }, { id: 'commons', name: 'The Commons', icon: '🎪', description: 'Festivals and resident gatherings.' },
] as const;

export function WorldAtlasView({ state, setState, onOpenTown, money }: { state: GameState; setState: React.Dispatch<React.SetStateAction<GameState | null>>; onOpenTown: () => void; money: (amount: number) => string; }) {
  const [zoom, setZoom] = useState<WorldScale>('town');
  const [cityName, setCityName] = useState('');
  const [cityFocus, setCityFocus] = useState<CivicFocus>('creative');
  const [notice, setNotice] = useState('');
  const world = normalizeWorld(state.world);
  const current = worldScale(state);
  const currentIndex = scaleOrder.indexOf(current);
  const activeIndex = scaleOrder.indexOf(zoom);
  const snapshot = cityEconomySnapshot(state.cityEconomy, state.businesses, state.townLevel);
  const civicBuildings = townBuildings.filter(b => (state.cityEconomy.buildings[b.id] ?? 0) > 0);
  const nextMilestone = worldMilestones.find(m => !world.milestones.includes(m.id));
  const activeEvent = currentWorldEvent(state);
  const incomeBonus = Math.round((worldIncomeMultiplier(state) - 1) * 100);
  const international = internationalBusinessSnapshot(state);
  const submitCity = (event: React.FormEvent) => {
    event.preventDefault();
    if (foundSatelliteCity(state, cityName, cityFocus) === state) { setNotice('Use a unique city name and reach Metropolis plus Metro Region first.'); return; }
    setState(currentState => currentState ? foundSatelliteCity(currentState, cityName, cityFocus) : currentState);
    setNotice(`${cityName.trim()} has joined your network.`); setCityName('');
  };
  return <main className="world-atlas">
    <header className="world-hero"><div><span className="world-kicker">SPEND IT ALL / LIVING WORLD ATLAS</span><h1>From one home to a universe.</h1><p>Build a place people live in. Districts, cities, policies, partnerships and planets all grow from the choices in your run.</p></div><div className="world-hero-stat"><span>CURRENT REACH</span><strong>{current}</strong><small>{state.cityEconomy.founded ? state.cityEconomy.townName : 'Uncharted Settlement'}</small><em>+{incomeBonus}% world economy</em></div></header>
    <nav className="world-zoom" aria-label="World scale">{zooms.map((entry, i) => <button key={entry.id} type="button" className={`${zoom === entry.id ? 'selected' : ''} ${i <= currentIndex ? 'reached' : ''}`} onClick={() => setZoom(entry.id)}><span>{entry.icon}</span><b>{entry.label}</b><small>{i <= currentIndex ? 'Reached' : 'Preview'}</small></button>)}</nav>
    <section className="world-main-grid"><div className="world-map-panel"><div className="world-panel-heading"><span>{zooms[activeIndex].icon} {zooms[activeIndex].label} view</span><span>{activeIndex <= currentIndex ? 'ACTIVE SCALE' : 'FUTURE MAP'}</span></div>
      {(zoom === 'town' || zoom === 'city') && <><div className="world-town-map" aria-label="Town district map">{districtLayout.map(d => { const open = d.id === 'hideout' || world.projects.includes(d.id as typeof world.projects[number]); return <div key={d.id} className={`world-map-lot ${open ? 'open' : 'planned'}`}><span>{d.icon}</span><b>{d.name}</b><small>{open ? d.description : 'Available to fund'}</small></div>; })}{civicBuildings.slice(0, 8).map(b => <div key={b.id} className="world-map-lot open civic"><span>{b.emoji}</span><b>{b.name}</b><small>×{state.cityEconomy.buildings[b.id]} in the capital</small></div>)}</div><div className="world-map-footer"><span>👥 {snapshot.population.toLocaleString()} residents</span><span>🏘️ {civicBuildings.length} building types</span><span>♥ {Math.round(snapshot.happiness)} happiness</span></div></>}
      {zoom === 'civilization' && <div className="world-diagram"><div className="world-orb civ">🏛️</div><h2>{world.focus ? `${civicFocuses.find(f => f.id === world.focus)?.name} Civilization` : 'A civilization takes shape'}</h2><p>Your policy board and civic events turn projects into a culture with its own direction.</p><div className="world-chip-row">{world.projects.map(id => <span key={id}>{worldProjects.find(p => p.id === id)?.icon} {worldProjects.find(p => p.id === id)?.name}</span>)}</div></div>}
      {(zoom === 'country' || zoom === 'empire') && <div className="world-diagram"><div className="world-orb globe">🌐</div><h2>{zoom === 'country' ? 'A connected country' : 'A network across the globe'}</h2><p>{state.cityEconomy.townName} is the capital. Your satellite cities bring their own specialty, projects and population to the network.</p><div className="world-network"><span>★ {state.cityEconomy.townName}</span>{world.cities.map(c => <span key={c.id}>↗ {c.name} · {civicFocuses.find(f => f.id === c.specialty)?.name}</span>)}</div></div>}
      {(zoom === 'planet' || zoom === 'universe') && <div className="world-diagram cosmic"><div className="world-orb planet">{zoom === 'planet' ? '🌎' : '🪐'}</div><h2>{zoom === 'planet' ? 'Your home world' : 'A growing star map'}</h2><p>Steward the home world, then develop each outpost according to its biome and unusual traits.</p><div className="world-chip-row"><span>🌎 Home world</span>{world.planets.map(p => <span key={p.id}>🪐 {p.name} · level {p.level}</span>)}</div></div>}</div>
      <aside className="world-side"><div className="world-card"><span className="world-kicker">YOUR NEXT HORIZON</span><h2>{nextMilestone?.name ?? (world.planets.length ? 'Grow the constellation' : 'First expedition')}</h2><p>{nextMilestone?.requirement ?? 'Develop your outposts and bring new worlds into the constellation.'}</p><div className="world-progress"><span style={{ width: `${((currentIndex + 1) / scaleOrder.length) * 100}%` }} /></div><small>{currentIndex + 1} of {scaleOrder.length} scales reached</small></div><div className="world-card"><span className="world-kicker">CONNECTED TO YOUR GAME</span><h2>Make the map grow</h2><p>Town buildings appear as lots. Projects reward civic resources. Cities and planetary work add a bounded bonus to the existing economy.</p><div className="world-side-actions"><button type="button" onClick={onOpenTown}>Open Town & Community →</button><a href="/cards">Visit Card Shop →</a></div></div></aside></section>

    <section className="world-actions"><div className="world-section-title"><span className="world-kicker">01 / LOCAL DEVELOPMENT</span><h2>Build places with a purpose</h2><p>Every finished district appears in the Atlas, raises goodwill and earns resources for future charters.</p></div>{!state.cityEconomy.founded && <div className="world-callout">Found your settlement in Town & Community to start construction. <button type="button" onClick={onOpenTown}>Go to Town →</button></div>}<div className="world-project-grid">{worldProjects.map(p => { const done = world.projects.includes(p.id); const available = p.available(state); return <article key={p.id} className={`world-project ${done ? 'complete' : ''}`}><span className="world-project-icon">{p.icon}</span><h3>{p.name}</h3><p>{p.description}</p><small>{done ? 'Built and contributing' : available ? `Rewards ${Object.entries(p.reward).map(([id, amount]) => `+${amount} ${worldResourceInfo[id as keyof typeof worldResourceInfo].name}`).join(' · ')}` : p.requirement}</small><button type="button" disabled={done || !canFundWorldProject(state, p.id)} onClick={() => setState(s => s ? fundWorldProject(s, p.id) : s)}>{done ? 'Built ✓' : `Fund · ${money(p.cost)}`}</button></article>; })}</div></section>

    <section className="world-actions"><div className="world-section-title"><span className="world-kicker">02 / CIVILIZATION IDENTITY</span><h2>What will your people be known for?</h2><p>Choose a focus once the town is founded. Satellite city specialties remain their own identity.</p></div><div className="world-focus-grid">{civicFocuses.map(f => <button type="button" key={f.id} disabled={!state.cityEconomy.founded || state.runStatus !== 'active'} className={world.focus === f.id ? 'chosen' : ''} onClick={() => setState(s => s ? chooseCivicFocus(s, f.id) : s)}><span>{f.icon}</span><b>{f.name}</b><small>{f.description}</small></button>)}</div></section>

    <section className="world-actions world-governance"><div className="world-section-title"><span className="world-kicker">03 / CIVIC LIFE</span><h2>Make choices that change the world</h2><p>Resources come from actual development. Policies and civic events turn them into an active simulation loop.</p></div><div className="world-resource-row">{Object.entries(worldResourceInfo).map(([id, info]) => <div key={id}><span>{info.icon}</span><b>{world.resources[id as keyof typeof world.resources]}</b><small>{info.name}</small></div>)}</div><div className="world-governance-grid"><div className="world-card"><h3>Policy board</h3><p>Policies can be changed whenever the conditions are met.</p><div className="world-policy-list">{worldPolicies.map(policy => { const active = world.policies.includes(policy.id); return <button type="button" key={policy.id} className={active ? 'active' : ''} disabled={!policy.requirement(state) || state.runStatus !== 'active'} onClick={() => setState(s => s ? toggleWorldPolicy(s, policy.id) : s)}><span>{policy.icon}</span><div><b>{policy.name}</b><small>{policy.description}</small></div><em>{active ? 'Active' : 'Adopt'}</em></button>; })}</div></div><div className="world-card world-event-card"><span className="world-kicker">CIVIC EVENT</span>{activeEvent ? <><h3>{activeEvent.icon} {activeEvent.title}</h3><p>{activeEvent.text}</p><div className="world-event-actions"><button type="button" onClick={() => setState(s => s ? resolveWorldEvent(s, 'support') : s)}>Support people<small>+Care, +Culture, goodwill</small></button><button type="button" onClick={() => setState(s => s ? resolveWorldEvent(s, 'balance') : s)}>Build balance<small>+Knowledge, +Influence</small></button><button type="button" onClick={() => setState(s => s ? resolveWorldEvent(s, 'venture') : s)}>Take a venture<small>+Discovery, +Influence</small></button></div></> : <><h3>Quiet day in the world</h3><p>Another civic event arrives when the game day advances or a new district opens.</p></>}</div></div></section>

    <section className="world-actions"><div className="world-section-title"><span className="world-kicker">04 / EXPANSION</span><h2>Link cities, build a country, reach the stars</h2></div><div className="world-expansion-grid"><div className="world-card"><h3>Satellite cities</h3><p>Unlocks at Metropolis and Metro Region. Each city grows over game days and can host its own initiatives.</p><div className="world-city-list">{world.cities.map(c => { const city = satelliteCitySnapshot(c, state.time.gameMinute, state.time.settings.dayLengthMinutes); const cost = satelliteCityUpgradeCost(c.level); return <div key={c.id}><div><b>{c.name} · Tier {c.level}</b><small>{c.specialty} · {city.population.toLocaleString()} residents · {city.jobs.toLocaleString()} jobs · {city.prosperity}% prosperity</small><div className="world-mini-actions">{['Night market', 'Civic clinic', 'Maker exchange'].map(initiative => <button type="button" key={initiative} disabled={c.projects.includes(initiative)} onClick={() => setState(s => s ? openCityInitiative(s, c.id, initiative) : s)}>{c.projects.includes(initiative) ? `${initiative} ✓` : initiative}</button>)}</div></div><button type="button" disabled={c.level >= 4 || state.cash < cost || state.runStatus !== 'active'} onClick={() => setState(s => s ? developSatelliteCity(s, c.id) : s)}>{c.level >= 4 ? 'Max tier' : `Develop · ${money(cost)}`}</button></div>; })}</div><form onSubmit={submitCity}><label htmlFor="atlas-city-name">New city name</label><input id="atlas-city-name" value={cityName} onChange={e => setCityName(e.target.value)} maxLength={32} placeholder="Name your new city" required /><label htmlFor="atlas-city-focus">City specialty</label><select id="atlas-city-focus" value={cityFocus} onChange={e => setCityFocus(e.target.value as CivicFocus)}>{civicFocuses.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select><button type="submit" disabled={!canFoundSatelliteCity(state)}>Found city · {money(750_000_000_000 * (world.cities.length + 1))}</button></form>{notice && <p role="status">{notice}</p>}</div>
      <div className="world-card"><h3>Country and diplomacy</h3><div className="world-diplomacy">{world.diplomacy.map(partner => <div key={partner.id}><span>{partner.icon}</span><div><b>{partner.name}</b><small>{partner.trust}% trust · {partner.specialty}</small></div><button type="button" disabled={partner.trust >= 100 || state.cash < 250_000_000 || state.runStatus !== 'active'} onClick={() => setState(s => s ? buildDiplomaticTrust(s, partner.id) : s)}>Build trust</button><button type="button" disabled={partner.compact || partner.trust < 60 || !world.milestones.includes('country')} onClick={() => setState(s => s ? formDiplomaticCompact(s, partner.id) : s)}>{partner.compact ? 'Compact ✓' : 'Compact'}</button></div>)}</div><div className="world-milestones">{worldMilestones.map(m => <div key={m.id}><span>{m.icon}</span><div><b>{m.name}</b><small>{world.milestones.includes(m.id) ? m.description : m.requirement}</small></div><button type="button" disabled={world.milestones.includes(m.id) || !milestoneAvailable(state, m.id) || state.cash < m.cost} onClick={() => setState(s => s ? claimWorldMilestone(s, m.id) : s)}>{world.milestones.includes(m.id) ? 'Established ✓' : money(m.cost)}</button></div>)}</div></div>
      <div className="world-card"><h3>Planetary expeditions</h3><p>Develop outposts through four stages while protecting stability in a world with its own biome and traits.</p><div className="world-planet-list">{world.planets.map(p => <div key={p.id}><span>🪐</span><div><b>{p.name} · Level {p.level}</b><small>{p.biome} · {p.stability}% stability · {p.traits.join(' · ')}</small></div><button type="button" disabled={p.level >= 4 || state.cash < planetaryUpgradeCost(p.level)} onClick={() => setState(s => s ? developPlanet(s, p.id) : s)}>{p.level >= 4 ? 'Mature ✓' : `Develop · ${money(planetaryUpgradeCost(p.level))}`}</button></div>)}</div><div className="world-milestones">{expeditionDestinations.map(d => <div key={d.name}><span>{d.icon}</span><div><b>{d.name}</b><small>{d.biome} · {d.description}</small></div><button type="button" disabled={!world.milestones.includes('planet') || !world.projects.includes('orbital-observatory') || world.planets.some(p => p.name === d.name) || state.cash < d.cost || state.runStatus !== 'active'} onClick={() => setState(s => s ? establishWorldOutpost(s, d.name) : s)}>{world.planets.some(p => p.name === d.name) ? 'Outpost ✓' : money(d.cost)}</button></div>)}</div></div></div></section>
    <section className="world-actions world-international"><div className="world-section-title"><span className="world-kicker">05 / INTERNATIONAL ECONOMY</span><h2>Turn diplomacy into businesses that travel</h2><p>Earn trust, open an embassy, establish a route, then sign a venture. Every active route feeds a bounded bonus back into the main economy.</p></div><div className="world-trade-summary"><div><b>{international.embassies}</b><small>embassies</small></div><div><b>{international.routes}</b><small>active route levels</small></div><div><b>{international.ventures}</b><small>global ventures</small></div><div><b>{international.reputation}%</b><small>average reputation</small></div><div><b>+{international.bonusPercent}%</b><small>international income</small></div></div><div className="world-market-grid">{world.foreignMarkets.map(market => { const sector = tradeSectors[market.sector]; const venture = globalVentures.find(v => v.marketId === market.id); const partner = world.diplomacy.find(p => p.id === market.id); return <article key={market.id} className={`world-market ${market.embassy ? 'connected' : ''}`}><div className="world-market-title"><span>{market.icon}</span><div><h3>{market.name}</h3><small>{market.region}</small></div></div><p>{sector.icon} {sector.name}: {sector.description}</p><div className="world-market-metrics"><span>{partner?.trust ?? 0}% trust</span><span>{market.reputation}% reputation</span><span>route {market.routeLevel}/3</span></div><div className="world-market-actions"><button type="button" disabled={market.embassy || !canOpenEmbassy(state, market.id)} onClick={() => setState(s => s ? openEmbassy(s, market.id) : s)}>{market.embassy ? 'Embassy open ✓' : `Open embassy · ${money(embassyCost(market.id))}`}</button><button type="button" disabled={!canUpgradeTradeRoute(state, market.id)} onClick={() => setState(s => s ? upgradeTradeRoute(s, market.id) : s)}>{market.routeLevel >= 3 ? 'Route mature ✓' : `Build route · ${money(tradeRouteCost(market.routeLevel))}`}</button></div>{venture && <div className="world-venture"><b>{venture.icon} {venture.name}</b><small>{venture.description}</small><button type="button" disabled={market.ventures.includes(venture.id) || !canSignGlobalVenture(state, venture.id)} onClick={() => setState(s => s ? signGlobalVenture(s, venture.id) : s)}>{market.ventures.includes(venture.id) ? 'Venture active ✓' : `Launch venture · ${money(venture.cost)}`}</button></div>}</article>; })}</div></section>
  </main>;
}
