import { artworks, type Artwork } from '@/data/artworks';
import type { ArtPortfolio } from '@/game/art-types';
import type { GameState } from '@/game/types';

export const createArtPortfolio=():ArtPortfolio=>({ownedIds:[],purchasePrices:{},displayedIds:[]});
export function normalizeArtPortfolio(input?:Partial<ArtPortfolio>):ArtPortfolio{const ownedIds=(input?.ownedIds??[]).filter((id,index,all)=>artworks.some((art)=>art.id===id)&&all.indexOf(id)===index);return{ownedIds,purchasePrices:input?.purchasePrices??{},displayedIds:(input?.displayedIds??[]).filter((id)=>ownedIds.includes(id))}}
export function artMarketMultiplier(art:Artwork,now=Date.now()){const week=Math.floor(now/604800000),seed=[...art.id].reduce((sum,char)=>sum+char.charCodeAt(0),0),wave=Math.sin((week+seed)*.79)*(art.kind==='local-original'?.16:.045),spike=art.kind==='local-original'&&(week+seed)%9===0?.12:0;return Math.max(.72,1+wave+spike)}
export function artValue(art:Artwork,now=Date.now()){return Math.round(art.basePrice*artMarketMultiplier(art,now))}
export function artPortfolioValue(portfolio?:ArtPortfolio,now=Date.now()){return normalizeArtPortfolio(portfolio).ownedIds.reduce((total,id)=>{const art=artworks.find((entry)=>entry.id===id);return total+(art?artValue(art,now):0)},0)}
export const artDisplayCapacity=(houseLevel:number)=>Math.max(1,houseLevel+1);
export function buyArtwork(state:GameState,id:string,now=Date.now()){const art=artworks.find((entry)=>entry.id===id),portfolio=normalizeArtPortfolio(state.art),price=art?artValue(art,now):0;if(!art||portfolio.ownedIds.includes(id)||state.cash<price||state.runStatus!=='active')return state;return{...state,cash:state.cash-price,totalSpent:state.totalSpent+price,art:{...portfolio,ownedIds:[...portfolio.ownedIds,id],purchasePrices:{...portfolio.purchasePrices,[id]:price}},lowestCash:Math.min(state.lowestCash,state.cash-price),updatedAt:now}}
export function sellArtwork(state:GameState,id:string,now=Date.now()){const art=artworks.find((entry)=>entry.id===id),portfolio=normalizeArtPortfolio(state.art);if(!art||!portfolio.ownedIds.includes(id)||state.runStatus!=='active')return state;const proceeds=Math.round(artValue(art,now)*.9);return{...state,cash:state.cash+proceeds,totalSold:state.totalSold+proceeds,art:{...portfolio,ownedIds:portfolio.ownedIds.filter((entry)=>entry!==id),displayedIds:portfolio.displayedIds.filter((entry)=>entry!==id)},updatedAt:now}}
export function toggleArtworkDisplay(state:GameState,id:string){const portfolio=normalizeArtPortfolio(state.art);if(!portfolio.ownedIds.includes(id))return state;const shown=portfolio.displayedIds,next=shown.includes(id)?shown.filter((entry)=>entry!==id):shown.length<artDisplayCapacity(state.houseLevel)?[...shown,id]:shown;return{...state,art:{...portfolio,displayedIds:next},updatedAt:Date.now()}}
