import { careerJobs } from '@/data/careers';
import type { CareerState } from '../career-types';
import type { GameState } from '../types';
import { lifeSkillLevel } from './life-progression';

export function createCareerState():CareerState{return{status:'unemployed',jobId:null,careerReputation:0,experienceDays:0,applications:0,promotions:0,lastPayday:0,lifetimeWages:0};}
export function normalizeCareer(input?:Partial<CareerState>|null):CareerState{return{...createCareerState(),...input,careerReputation:Math.max(0,input?.careerReputation??0),experienceDays:Math.max(0,input?.experienceDays??0),applications:Math.max(0,input?.applications??0),promotions:Math.max(0,input?.promotions??0),lifetimeWages:Math.max(0,input?.lifetimeWages??0)};}
export function currentCareerJob(state:Pick<GameState,'career'>){const career=normalizeCareer(state.career);return careerJobs.find(j=>j.id===career.jobId)??null;}
export function careerJobUnlocked(state:Pick<GameState,'life'|'career'>,jobId:string){const job=careerJobs.find(j=>j.id===jobId);if(!job)return false;const career=normalizeCareer(state.career);if(!state.life.enabled)return true;return lifeSkillLevel(state.life,job.requiredSkillId??'general-labor')>=(job.requiredSkillLevel??0)&&career.careerReputation>=(job.requiredReputation??0);}
export function applyForCareer(state:GameState,jobId:string):GameState{if(!careerJobUnlocked(state,jobId))return state;const career=normalizeCareer(state.career);return{...state,career:{...career,status:'employed',jobId,applications:career.applications+1,lastPayday:Math.floor(state.time.gameMinute/Math.max(1,state.time.settings.dayLengthMinutes))},updatedAt:Date.now()};}
export function leaveCareer(state:GameState):GameState{return{...state,career:{...normalizeCareer(state.career),status:'unemployed',jobId:null},updatedAt:Date.now()};}
export function promoteCareer(state:GameState):GameState{const career=normalizeCareer(state.career);const current=careerJobs.find(j=>j.id===career.jobId);if(!current?.nextJobId||!careerJobUnlocked(state,current.nextJobId))return state;return{...state,career:{...career,jobId:current.nextJobId,promotions:career.promotions+1},updatedAt:Date.now()};}
export function advanceCareerPay(state:GameState,previousGameMinute:number,nextGameMinute:number):GameState{const career=normalizeCareer(state.career);if(career.status!=='employed'||!career.jobId||!state.time.settings.enabled)return{...state,career};const job=careerJobs.find(j=>j.id===career.jobId);if(!job)return{...state,career};const dayLength=Math.max(1,state.time.settings.dayLengthMinutes);const currentDay=Math.floor(nextGameMinute/dayLength);const dueDays=Math.max(0,currentDay-career.lastPayday);if(!dueDays)return{...state,career};const wages=job.payPerDay*dueDays;return{...state,cash:state.cash+wages,lifetimeIncome:state.lifetimeIncome+wages,career:{...career,lastPayday:currentDay,lifetimeWages:career.lifetimeWages+wages,experienceDays:career.experienceDays+dueDays,careerReputation:career.careerReputation+dueDays}};}
