import { careerJobs } from '@/data/careers';
import type { CareerState } from '../career-types';
import type { GameState } from '../types';
import { lifeSkillLevel } from './life-progression';
import { hasCredential } from './education';
export function createCareerState():CareerState{return{status:'unemployed',jobId:null,careerReputation:0,experienceDays:0,applications:0,promotions:0,lastPayday:0,lifetimeWages:0,performance:50,raiseMultiplier:1,raises:0,daysInCurrentJob:0,jobsHeld:0,voluntaryQuits:0,layoffs:0,fired:0,unemploymentDays:0};}
export function normalizeCareer(input?:Partial<CareerState>|null):CareerState{const b=createCareerState();return{...b,...input,careerReputation:Math.max(0,input?.careerReputation??0),experienceDays:Math.max(0,input?.experienceDays??0),applications:Math.max(0,input?.applications??0),promotions:Math.max(0,input?.promotions??0),lifetimeWages:Math.max(0,input?.lifetimeWages??0),performance:Math.max(0,Math.min(100,input?.performance??50)),raiseMultiplier:Math.max(1,input?.raiseMultiplier??1),raises:Math.max(0,input?.raises??0),daysInCurrentJob:Math.max(0,input?.daysInCurrentJob??0),jobsHeld:Math.max(0,input?.jobsHeld??0),voluntaryQuits:Math.max(0,input?.voluntaryQuits??0),layoffs:Math.max(0,input?.layoffs??0),fired:Math.max(0,input?.fired??0),unemploymentDays:Math.max(0,input?.unemploymentDays??0)};}
export function currentCareerJob(state:Pick<GameState,'career'>){const c=normalizeCareer(state.career);return careerJobs.find(j=>j.id===c.jobId)??null;}
export function careerQualificationMet(state:GameState,jobId:string){const j=careerJobs.find(x=>x.id===jobId);if(!j?.qualification)return true;const q=j.qualification,c=normalizeCareer(state.career),skill=lifeSkillLevel(state.life,j.requiredSkillId??'general-labor');const credential=!!q.credentialId&&hasCredential(state,q.credentialId),experienced=c.experienceDays>=(q.experienceDays??Infinity),selfTaught=skill>=(q.alternativeSkillLevel??Infinity);return credential||experienced||selfTaught;}
export function careerJobUnlocked(state:GameState,jobId:string){const j=careerJobs.find(x=>x.id===jobId);if(!j)return false;const c=normalizeCareer(state.career);if(!state.life.enabled)return true;return lifeSkillLevel(state.life,j.requiredSkillId??'general-labor')>=(j.requiredSkillLevel??0)&&c.careerReputation>=(j.requiredReputation??0)&&careerQualificationMet(state,jobId);}
export function applyForCareer(state:GameState,jobId:string):GameState{if(!careerJobUnlocked(state,jobId))return state;const c=normalizeCareer(state.career);return{...state,career:{...c,status:'employed',jobId,applications:c.applications+1,lastPayday:Math.floor(state.time.gameMinute/Math.max(1,state.time.settings.dayLengthMinutes)),performance:50,raiseMultiplier:1,daysInCurrentJob:0,jobsHeld:c.jobsHeld+(c.jobId===jobId?0:1)},updatedAt:Date.now()};}
export function leaveCareer(state:GameState):GameState{const c=normalizeCareer(state.career);return{...state,career:{...c,status:'unemployed',jobId:null,performance:50,raiseMultiplier:1,daysInCurrentJob:0,voluntaryQuits:c.voluntaryQuits+1},updatedAt:Date.now()};}
export function promoteCareer(state:GameState):GameState{const c=normalizeCareer(state.career),cur=careerJobs.find(j=>j.id===c.jobId);if(!cur?.nextJobId||!careerJobUnlocked(state,cur.nextJobId)||c.performance<65)return state;return{...state,career:{...c,jobId:cur.nextJobId,promotions:c.promotions+1,raiseMultiplier:1,daysInCurrentJob:0,performance:Math.max(55,c.performance-10)},updatedAt:Date.now()};}
export function requestCareerRaise(state:GameState):GameState{const c=normalizeCareer(state.career);if(c.status!=='employed'||c.daysInCurrentJob<10||c.performance<70)return state;const bump=c.performance>=90?.12:c.performance>=80?.08:.05;return{...state,career:{...c,raiseMultiplier:c.raiseMultiplier*(1+bump),raises:c.raises+1,performance:Math.max(50,c.performance-12)},updatedAt:Date.now()};}
export function careerDailyPay(state:GameState){const c=normalizeCareer(state.career),j=careerJobs.find(x=>x.id===c.jobId);return j?j.payPerDay*c.raiseMultiplier:0;}
export function advanceCareerPay(state:GameState,_p:number,next:number):GameState{const c=normalizeCareer(state.career);if(!state.time.settings.enabled)return{...state,career:c};const dl=Math.max(1,state.time.settings.dayLengthMinutes),day=Math.floor(next/dl),due=Math.max(0,day-c.lastPayday);if(!due)return{...state,career:c};if(c.status!=='employed'||!c.jobId)return{...state,career:{...c,lastPayday:day,unemploymentDays:c.unemploymentDays+due}};const j=careerJobs.find(x=>x.id===c.jobId);if(!j)return{...state,career:{...c,status:'unemployed',jobId:null,lastPayday:day}};const sl=lifeSkillLevel(state.life,j.requiredSkillId??'general-labor'),performance=Math.max(0,Math.min(100,c.performance+due*(sl>=(j.requiredSkillLevel??0)+2?2:1))),wages=j.payPerDay*c.raiseMultiplier*due;let nc:CareerState={...c,lastPayday:day,lifetimeWages:c.lifetimeWages+wages,experienceDays:c.experienceDays+due,daysInCurrentJob:c.daysInCurrentJob+due,careerReputation:c.careerReputation+due,performance};if(nc.daysInCurrentJob>=7&&nc.performance<20)nc={...nc,status:'unemployed',jobId:null,fired:nc.fired+1,careerReputation:Math.max(0,nc.careerReputation-5),daysInCurrentJob:0,raiseMultiplier:1};else if(nc.daysInCurrentJob>=30&&((day+nc.jobsHeld*7)%97===0))nc={...nc,status:'unemployed',jobId:null,layoffs:nc.layoffs+1,daysInCurrentJob:0,raiseMultiplier:1};return{...state,cash:state.cash+wages,lifetimeIncome:state.lifetimeIncome+wages,career:nc};}