import { careerJobs } from '@/data/careers';
import type { CareerState } from '../career-types';
import type { GameState } from '../types';
import { lifeSkillLevel } from './life-progression';

export function createCareerState():CareerState{return{status:'unemployed',jobId:null,careerReputation:0,experienceDays:0,applications:0,promotions:0,lastPayday:0,lifetimeWages:0,performance:50,raiseMultiplier:1,raises:0,daysInCurrentJob:0,jobsHeld:0,voluntaryQuits:0,layoffs:0,fired:0,unemploymentDays:0};}
export function normalizeCareer(input?:Partial<CareerState>|null):CareerState{const base=createCareerState();return{...base,...input,careerReputation:Math.max(0,input?.careerReputation??0),experienceDays:Math.max(0,input?.experienceDays??0),applications:Math.max(0,input?.applications??0),promotions:Math.max(0,input?.promotions??0),lifetimeWages:Math.max(0,input?.lifetimeWages??0),performance:Math.max(0,Math.min(100,input?.performance??50)),raiseMultiplier:Math.max(1,input?.raiseMultiplier??1),raises:Math.max(0,input?.raises??0),daysInCurrentJob:Math.max(0,input?.daysInCurrentJob??0),jobsHeld:Math.max(0,input?.jobsHeld??0),voluntaryQuits:Math.max(0,input?.voluntaryQuits??0),layoffs:Math.max(0,input?.layoffs??0),fired:Math.max(0,input?.fired??0),unemploymentDays:Math.max(0,input?.unemploymentDays??0)};}
export function currentCareerJob(state:Pick<GameState,'career'>){const c=normalizeCareer(state.career);return careerJobs.find(j=>j.id===c.jobId)??null;}
export function careerJobUnlocked(state:Pick<GameState,'life'|'career'>,jobId:string){const j=careerJobs.find(x=>x.id===jobId);if(!j)return false;const c=normalizeCareer(state.career);if(!state.life.enabled)return true;return lifeSkillLevel(state.life,j.requiredSkillId??'general-labor')>=(j.requiredSkillLevel??0)&&c.careerReputation>=(j.requiredReputation??0);}
export function applyForCareer(state:GameState,jobId:string):GameState{if(!careerJobUnlocked(state,jobId))return state;const c=normalizeCareer(state.career);return{...state,career:{...c,status:'employed',jobId,applications:c.applications+1,lastPayday:Math.floor(state.time.gameMinute/Math.max(1,state.time.settings.dayLengthMinutes)),performance:50,raiseMultiplier:1,daysInCurrentJob:0,jobsHeld:c.jobsHeld+(c.jobId===jobId?0:1)},updatedAt:Date.now()};}
export function leaveCareer(state:GameState):GameState{const c=normalizeCareer(state.career);return{...state,career:{...c,status:'unemployed',jobId:null,performance:50,raiseMultiplier:1,daysInCurrentJob:0,voluntaryQuits:c.voluntaryQuits+1},updatedAt:Date.now()};}
export function promoteCareer(state:GameState):GameState{const c=normalizeCareer(state.career),cur=careerJobs.find(j=>j.id===c.jobId);if(!cur?.nextJobId||!careerJobUnlocked(state,cur.nextJobId)||c.performance<65)return state;return{...state,career:{...c,jobId:cur.nextJobId,promotions:c.promotions+1,raiseMultiplier:1,daysInCurrentJob:0,performance:Math.max(55,c.performance-10)},updatedAt:Date.now()};}
export function requestCareerRaise(state:GameState):GameState{const c=normalizeCareer(state.career);if(c.status!=='employed'||c.daysInCurrentJob<10||c.performance<70)return state;const bump=c.performance>=90?.12:c.performance>=80?.08:.05;return{...state,career:{...c,raiseMultiplier:c.raiseMultiplier*(1+bump),raises:c.raises+1,performance:Math.max(50,c.performance-12)},updatedAt:Date.now()};}
export function careerDailyPay(state:GameState){const c=normalizeCareer(state.career),j=careerJobs.find(x=>x.id===c.jobId);return j?j.payPerDay*c.raiseMultiplier:0;}
export function advanceCareerPay(state:GameState,_previousGameMinute:number,nextGameMinute:number):GameState{const c=normalizeCareer(state.career);if(!state.time.settings.enabled)return{...state,career:c};const dayLength=Math.max(1,state.time.settings.dayLengthMinutes),currentDay=Math.floor(nextGameMinute/dayLength),dueDays=Math.max(0,currentDay-c.lastPayday);if(!dueDays)return{...state,career:c};if(c.status!=='employed'||!c.jobId)return{...state,career:{...c,lastPayday:currentDay,unemploymentDays:c.unemploymentDays+dueDays}};const j=careerJobs.find(x=>x.id===c.jobId);if(!j)return{...state,career:{...c,status:'unemployed',jobId:null,lastPayday:currentDay}};let performance=c.performance;const skillLevel=lifeSkillLevel(state.life,j.requiredSkillId??'general-labor');performance=Math.max(0,Math.min(100,performance+dueDays*(skillLevel>=(j.requiredSkillLevel??0)+2?2:1)));
 const wages=j.payPerDay*c.raiseMultiplier*dueDays;let nextCareer:CareerState={...c,lastPayday:currentDay,lifetimeWages:c.lifetimeWages+wages,experienceDays:c.experienceDays+dueDays,daysInCurrentJob:c.daysInCurrentJob+dueDays,careerReputation:c.careerReputation+dueDays,performance};
 // Poor sustained performance can end employment; otherwise rare deterministic economic layoffs prevent careers from being risk-free forever.
 if(nextCareer.daysInCurrentJob>=7&&nextCareer.performance<20){nextCareer={...nextCareer,status:'unemployed',jobId:null,fired:nextCareer.fired+1,careerReputation:Math.max(0,nextCareer.careerReputation-5),daysInCurrentJob:0,raiseMultiplier:1};}
 else if(nextCareer.daysInCurrentJob>=30&&((currentDay+nextCareer.jobsHeld*7)%97===0)){nextCareer={...nextCareer,status:'unemployed',jobId:null,layoffs:nextCareer.layoffs+1,daysInCurrentJob:0,raiseMultiplier:1};}
 return{...state,cash:state.cash+wages,lifetimeIncome:state.lifetimeIncome+wages,career:nextCareer};}
