import { educationPrograms } from '@/data/education';
import type { EducationState,CredentialId } from '../education-types';
import type { GameState } from '../types';
import { gainLifeSkillXp,lifeSkillLevel } from './life-progression';
export function createEducationState():EducationState{return{credentials:[],activeCredentialId:null,studyDaysRemaining:0,lifetimeTuition:0,completedPrograms:0};}
export function normalizeEducation(input?:Partial<EducationState>|null):EducationState{return{...createEducationState(),...input,credentials:Array.from(new Set(input?.credentials??[])),studyDaysRemaining:Math.max(0,input?.studyDaysRemaining??0),lifetimeTuition:Math.max(0,input?.lifetimeTuition??0),completedPrograms:Math.max(0,input?.completedPrograms??0)};}
export function canEnroll(state:GameState,id:CredentialId){const e=normalizeEducation(state.education),p=educationPrograms.find(x=>x.id===id);return !!p&&!e.activeCredentialId&&!e.credentials.includes(id)&&state.cash>=p.cost&&lifeSkillLevel(state.life,p.skillId)>=p.requiredSkillLevel;}
export function enrollEducation(state:GameState,id:CredentialId):GameState{if(!canEnroll(state,id))return state;const p=educationPrograms.find(x=>x.id===id)!;return{...state,cash:state.cash-p.cost,totalSpent:state.totalSpent+p.cost,education:{...normalizeEducation(state.education),activeCredentialId:id,studyDaysRemaining:p.studyDays,lifetimeTuition:normalizeEducation(state.education).lifetimeTuition+p.cost},updatedAt:Date.now()};}
export function advanceEducation(state:GameState,previousMinute:number,nextMinute:number):GameState{const e=normalizeEducation(state.education);if(!state.time.settings.enabled||!e.activeCredentialId)return{...state,education:e};const day=Math.max(1,state.time.settings.dayLengthMinutes),days=Math.max(0,Math.floor(nextMinute/day)-Math.floor(previousMinute/day));if(!days)return{...state,education:e};const remaining=Math.max(0,e.studyDaysRemaining-days);if(remaining>0)return{...state,education:{...e,studyDaysRemaining:remaining}};const p=educationPrograms.find(x=>x.id===e.activeCredentialId);if(!p)return{...state,education:{...e,activeCredentialId:null,studyDaysRemaining:0}};return{...state,life:gainLifeSkillXp(state.life,p.skillId,p.skillXp),education:{...e,credentials:[...e.credentials,p.id],activeCredentialId:null,studyDaysRemaining:0,completedPrograms:e.completedPrograms+1}};}
export function hasCredential(state:Pick<GameState,'education'>,id:CredentialId){return normalizeEducation(state.education).credentials.includes(id);}