// VENDORED from Lok-EcoSystsem/universe-sdk -- DO NOT EDIT HERE. Edit the SDK and run sync-sdk.sh.
import { combatForRarity } from "./combat";
import { SCHEMA_VERSION, type CardArtRecipe, type CardCombat, type PlatformManifest, type RegistryRarity } from "./types";

/**
 * Publisher helpers. A platform's whole integration is a function that maps
 * its own content into `PublishCard[]`; these turn that into the idempotent
 * SQL the shared project applies. Pure string building: no fs, no deps.
 */
export interface PublishCard {
  /** Unique within the platform; becomes asset_id = `${namespace}:${slug}`. */
  slug: string;
  name: string;
  description?: string | null;
  rarity: RegistryRarity;
  setId: string;
  setName?: string | null;
  cardNumber?: string | null;
  tags?: string[];
  /** Used for the default combat block when `combat` is omitted. */
  role?: CardCombat["role"];
  combat?: CardCombat | null;
  art?: CardArtRecipe | null;
  /** Extra manifest metadata (stats, species...). */
  metadata?: Record<string, unknown>;
  acquisition?: string[];
  kind?: string;
}

export interface PublishItem {
  sku: string;
  name: string;
  description?: string | null;
  price: number;
  rarity?: string | null;
  /** lok_item_type enum value: theme, cursor, ui_kit, motion_pack, tool, boost, badge, sfx, title, frame, pet, cosmetic */
  itemType: string;
  payload: Record<string, unknown>;
  requiresRank?: string | null;
}

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

export function buildCardsSql(platform: PlatformManifest, cards: PublishCard[]): string {
  const slugs = new Set<string>();
  const rows = cards.map((c) => {
    if (slugs.has(c.slug)) throw new Error(`duplicate slug ${c.slug}`);
    slugs.add(c.slug);
    const id = `${platform.namespace}:${c.slug}`;
    const manifest = {
      schema: "lok.asset", schemaVersion: 1, id, namespace: platform.namespace, slug: c.slug, kind: c.kind ?? "card", version: 1,
      name: c.name, description: c.description ?? undefined, rarity: c.rarity, tags: c.tags ?? [], acquisition: c.acquisition ?? [],
      ownership: { transferPolicy: "soulbound", uniqueInstance: false, stackable: false, requiresServerAuthorityForTransfer: true, survivesRunReset: true },
      provenance: { sourceGame: platform.namespace }, metadata: { cardNumber: c.cardNumber ?? undefined, setId: c.setId, ...(c.metadata ?? {}) },
    };
    const combat = c.combat === undefined ? combatForRarity(c.rarity, c.role ?? "hero") : c.combat;
    return `(${q(id)},${q(platform.appKey)},${q(platform.namespace)},${q(c.setId)},${q(c.setName ?? null)},${q(c.cardNumber ?? null)},${q(c.kind ?? "card")},${q(c.name)},${q(c.description ?? null)},${q(c.rarity)},array[${(c.tags ?? []).map(q).join(",")}]::text[],${j(combat)},${j(c.art ?? null)},${j(manifest)},${SCHEMA_VERSION})`;
  });
  return `-- Generated by @lok/universe-sdk publish -- do not hand-edit. Platform: ${platform.appKey}
insert into public.lok_cards (asset_id,source_game,namespace,set_id,set_name,card_number,kind,name,description,rarity,tags,combat,art,manifest,schema_version)
values
${rows.join(",\n")}
on conflict (asset_id) do update set
  set_id=excluded.set_id, set_name=excluded.set_name, card_number=excluded.card_number, name=excluded.name,
  description=excluded.description, rarity=excluded.rarity, tags=excluded.tags, combat=excluded.combat, art=excluded.art,
  manifest=excluded.manifest, schema_version=excluded.schema_version, active=true, updated_at=now();
-- Cards this platform no longer publishes are retired (hidden), never deleted, so collections keep working.
${cards.length
    ? `update public.lok_cards set active=false, updated_at=now()
  where source_game=${q(platform.appKey)} and active and asset_id not in (${cards.map((c) => q(`${platform.namespace}:${c.slug}`)).join(",")});`
    : "-- (no cards published; nothing retired)"}
`;
}

export function buildCatalogSql(platform: PlatformManifest, items: PublishItem[]): string {
  const rows = items.map((i) => `((select id from public.lok_tenants limit 1),${q(i.sku)},array[${q(platform.appKey)}],${q(i.itemType)}::lok_item_type,${q(i.name)},${q(i.description ?? null)},${Math.round(i.price)},${q(i.rarity ?? null)},${j(i.payload)},${q(i.requiresRank ?? null)},true)`);
  return `-- Generated by @lok/universe-sdk publish -- do not hand-edit. Platform: ${platform.appKey}
-- Prices seed NEW items only. An existing row keeps its live price, so repricing in the database is never undone by a republish.
insert into public.lok_catalog (tenant_id,sku,app_scope,item_type,name,description,price,rarity,payload,requires_rank,active)
values
${rows.join(",\n")}
on conflict (tenant_id, sku) do update set
  name=excluded.name, description=excluded.description, rarity=excluded.rarity, payload=excluded.payload;
`;
}
