/**
 * Publisher for the LOK Card Universe (see Lok-EcoSystsem/LokToken EcoSystem/
 * LOK_CARD_UNIVERSE.md). Projects the Firstlight LOKdex into SQL for the
 * shared `lok_cards` registry, with each card's pixel-grid sprite as its art
 * recipe so every other LOK game can redraw the real model.
 *
 *   npx tsx scripts/export-lok-registry.ts <outDir>
 *
 * Idempotent: re-run after content changes and apply the output. Combat is
 * left null -- the registry fills a rarity-based default.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { lokDexEntries } from '../data/lokdex';
import { lokDexReleases } from '../data/lokdex-editions';
import { pixelPetSprites } from '../data/pixel-pet-sprites';
import { pixelPetSpritesWave2 } from '../data/pixel-pet-sprites-wave2';
import { pixelPetSpritesWave3 } from '../data/pixel-pet-sprites-wave3';

const APP_KEY = 'spendutall';
const NS = 'g6.spend-it-all';
const q = (value: string | null | undefined) => (value == null ? 'null' : `'${value.replace(/'/g, "''")}'`);
const j = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`;

const sprites = [...pixelPetSprites, ...pixelPetSpritesWave2, ...pixelPetSpritesWave3];
const spriteFor = (entry: (typeof lokDexEntries)[number]) =>
  sprites.find((sprite) => sprite.aliases?.includes(entry.id) || sprite.petId === entry.companionCustomizationId);

const rows = lokDexEntries.map((entry) => {
  const slug = entry.id.replace(/:/g, '-');
  const assetId = `${NS}:${slug}`;
  const sprite = spriteFor(entry);
  const art = sprite ? { kind: 'pixel-grid', grid: sprite.grid, palette: sprite.palette, motion: sprite.animation.idle } : null;
  const release = lokDexReleases.find((candidate) => candidate.id === entry.setId);
  const cardNumber = String(entry.number).padStart(3, '0');
  const manifest = {
    schema: 'lok.asset',
    schemaVersion: 1,
    id: assetId,
    namespace: NS,
    slug,
    kind: 'card',
    version: 1,
    name: entry.name,
    description: entry.description,
    rarity: entry.rarity,
    tags: entry.tags,
    acquisition: entry.acquisition,
    ownership: { transferPolicy: 'giftable', uniqueInstance: true, stackable: false, requiresServerAuthorityForTransfer: true, survivesRunReset: true },
    provenance: { sourceGame: NS },
    metadata: { species: entry.species, generation: entry.generation, cardNumber, powerProfile: { ...entry.cardStats } },
  };
  return `(${q(assetId)},${q(APP_KEY)},${q(NS)},${q(entry.setId)},${q(release?.name ?? entry.setId)},${q(cardNumber)},'card',${q(entry.name)},${q(entry.description)},${q(entry.rarity)},array[${entry.tags.map(q).join(',')}]::text[],null,${j(art)},${j(manifest)})`;
});

const sql = `-- Generated by scripts/export-lok-registry.ts -- do not hand-edit.
insert into public.lok_cards (asset_id,source_game,namespace,set_id,set_name,card_number,kind,name,description,rarity,tags,combat,art,manifest)
values
${rows.join(',\n')}
on conflict (asset_id) do update set
  set_id=excluded.set_id, set_name=excluded.set_name, card_number=excluded.card_number, name=excluded.name,
  description=excluded.description, rarity=excluded.rarity, tags=excluded.tags, art=excluded.art,
  manifest=excluded.manifest, updated_at=now();
`;

const outDir = process.argv[2] ?? '.';
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'spendutall.cards.sql'), sql);
console.log(`${rows.length} cards (${rows.filter((row) => !row.includes(`'{"kind"`)).length} without art) -> ${outDir}`);
